name: Deploy to CentOS Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and package
        run: |
          # 执行打包操作，生成 dist 文件夹
          pnpm install
          pnpm run build
          tar czf dist.tar.gz dist

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          source: './dist.tar.gz'
          target: ${{ secrets.REMOTE_TARGET }}

      - name: SSH to server and extract files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            tar xzf dist.tar.gz
            rm dist.tar.gz
